DELIMITER $$
USE prueba $$
DROP PROCEDURE IF EXISTS proc $$
CREATE PROCEDURE proc(param INT)
BEGIN
	DECLARE var1;
	SET var1 = param + 1;
	IF var1 = 1 THEN INSERT INTO T VALUES (param);
	END IF;
	IF param = 0 THEN UPDATE T SET s1 = s1 + 1;
	ELSE UPDATE T SET s1 = s1 + 2;
	END IF;
END; $$
DELIMITER;
